# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
install:
  - sudo apt-get install -y python3.7
  - sudo apt-get -y install python3-pip
  - pip install cloud-volume~=1.20.1
  - pip3 install git+git://github.com/schlegelp/skeletor@master
os:
  - linux
#  - osx
r:
#  - oldrel
  - release
cache: packages
addons:
  apt:
    packages:
    - libglu1-mesa-dev
r_check_args: --no-manual # --no-build-vignettes
env:
  global:
    - RGL_USE_NULL=TRUE
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
before_install:
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
after_success:
  - Rscript -e 'covr::coveralls()'
